version: '3.7'
services:
  web:
    build: '.'
    ports:
      - "4000:4000"
    volumes:
      - /opt/app/assets/node_modules
      - /opt/app/deps
      - .:/opt/app
    depends_on:
      - db
    environment:
      MIX_ENV: 'dev'
  db:
    image: mdillon/postgis
    volumes:
      - '~/postgres-data:/var/lib/postgresql/data'
    ports:
      - 5432:5432